config/routes.rb
Rails.application.routes.draw do
  resources :posts

  get "/changelanguage", to: "set_language#change_language"
  get "dashboard/index"
  get "device_code/show"
  get "get_device_code/show"
  get "assignment_device/show"
  get "group_category/show"
  get "device_assign/show"
  get "requests/new"
  get "requests/add_request_detail"
  root "dashboard#index"
  delete "/requestdetails", to: "request_details#destroy"
  get "/home", to: "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/help", to: "static_pages#help"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "show", to: :show, controller: "return_devices"
  put "update", to: :update, controller: "return_devices",
   collection: {update: :put}
  get "/dashboard_chart", to: "dashboard#request_chart"

  resources :users
  resources :devices
  resources :requests
  resources :request_details
  resources :assignments
  resources :notifications
  resources :request_status
  resources :my_devices, only: :index
  resources :user_setting, only: [:index, :update], collection: {update: :put}
  resources :return_devices, only: :index
  resources :device_history
  resources :user_groups
  resources :dashboard
  resources :device_categories
  resources :user_profiler
  resources :request_row
  resources :set_language
  resources :import
  resources :exports
  resources :printed_codes do
    patch :update, on: :collection
  end

  namespace :api do
    resources :devices, only: :index
  end

  put "create", to: :create, controller: "import",
    collection: {create: :put}
  mount ActionCable.server => "/cable"
  resources :export
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :logged_in_user

  def index
    load_request_dashboard false
    load_device_dashboard false
  end

  def request_chart
    case params[:type]
    when Settings.chart_type.request
      load_request_dashboard true
    when Settings.chart_type.device
      load_device_dashboard true
    else
      json_response false, t("dashboard.not_supply")
    end
  end

  private

  def load_device_dashboard isRemote
    if @current_user.can_manage_device
      @device_categories = DeviceCategory.all
      @device_categories.each do |cat|
        cat.extend_dashboard_data
      end
      @device_categories = @device_categories.sort_by {|obj| -obj.device_total}
        .sort_by {|obj| -obj.using_percent}
        .sort_by {|obj| -obj.device_assignment}
        .first(Settings.top_dashboard)
      @device_chartobj = DeviceStatus.calculate_device_dashboard
      isRemote ? json_request_chart_response(true, @device_chartobj) : @device_chartobj
    end
  end

  def load_request_dashboard isRemote
    user_id = nil
    case @current_user.current_permission
    when Settings.action.done, Settings.action.waiting_done, Settings.action.approve
      @request = get_request_top unless isRemote
    else
      @requests = get_my_requests_top unless isRemote
      user_id = @current_user.id
    end
    @chartobj = RequestStatus.calculate_request_dashboard user_id, @current_user
    isRemote ? json_request_chart_response(true, @chartobj) : @chartobj
  end

  def get_my_requests_top
    Request.of_for_user(@current_user.id, @current_user.default_parent_path,
      @current_user).order_by_time
      .first(Settings.top_dashboard)
      .sort_by {|obj| obj.request_status_id}
  end

  def get_request_top
    @requests = Request.request_manage(@current_user.default_parent_path,
      @current_user)
      .request_not_self(@current_user)
      .order_by_time
      .first(Settings.top_dashboard)
      .sort_by {|obj| obj.request_status_id}
  end
end

app/views/dashboard/_admin_overview.html.erb
<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 col-xl-12">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2><span><%= t "dashboard.admin" %></span></h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <div class="tile_info">
              <%= link_to t("dashboard.import"),  import_index_path %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/_chart_overview.html.erb
<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="row">
    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12 col-xl-12">
      <% if current_user.have_request_action %>
        <%= render "request_cycle" %>
      <% end %>
    </div>
    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12 col-xl-12">
      <% if current_user.can_manage_device %>
        <%= render "device_cycle" %>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboard/_device_cycle.html.erb
<div id="device_cycle">
  <div class="x_panel tile fixed_height_320 overflow_hidden">
    <div class="x_title">
      <h3>
        <span><%= t "dashboard.device_overview" %> </span>
        <%= link_to t("dashboard.device.to_device"),  devices_path %>
      </h3>
      <ul class="nav navbar-right panel_toolbox">
        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
        </li>
      </ul>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
    <% if @device_chartobj.present? && @device_chartobj[:have_data] %>
      <table class="chart w-100">
        <tr>
          <th class="w-37">
            <p><%= t "dashboard.device.chart" %></p>
          </th>
          <th>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
              <p class=""><%= t "dashboard.device.status" %></p>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
              <p class=""><%= t "dashboard.device.summary" %></p>
            </div>
          </th>
        </tr>
        <tr>
          <td>
            <canvas id="device_canvas"></canvas>
          </td>
          <td>
            <table class="tile_info">
              <% @device_chartobj[:labels].count.times do |i| %>
                <tr>
                  <td>
                    <p>
                      <i class="fa fa-square <%= @device_chartobj[:colors][i]%>"></i>
                      <%= link_to @device_chartobj[:labels][i],
                        devices_path(status_id: @device_chartobj[:device_status][i]) %>
                    </p>
                  </td>
                  <td><%= @device_chartobj[:datapercent][i] %>%</td>
                </tr>
              <% end %>
            </table>
          </td>
        </tr>
      </table>
    <% else %>
      <div class="tile_info">
        <%= link_to t("dashboard.request.go_to_device"),  devices_path %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/dashboard/_device_overview.html.erb
<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2><span><%= t "dashboard.device_overview" %></span></h2>
      <ul class="nav navbar-right panel_toolbox">
        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
        </li>
      </ul>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <%= render "device_cycle" %>
      <%= render "grid_device_dashboard" %>
    </div>
  </div>
</div>

app/views/dashboard/_grid_device_dashboard.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= t "dashboard.device.check" %></th>
      <th><%= t "dashboard.device.name" %></th>
      <th class="horizital_progress"><%= t "dashboard.device.status" %></th>
      <th><%= t "dashboard.device.table.summary_title" %></th>
    </tr>
  </thead>
  <tbody>
    <% @device_categories.each do |category| %>
      <tr>
        <td><%= link_to t("dashboard.device.view"),
          devices_path(category_id: category.id) %></td>
        <td><%= category.name %></td>
        <td class="project_progress">
          <div class="progress progress_sm">
            <div class="progress-bar bg-green" role="progressbar"
              data-transitiongoal="<%= category.using_percent%>"
              aria-valuenow="<%= category.using_percent%>"
              style="width: <%= category.using_percent%>%;"></div>
          </div>
          <small><%= category.using_percent %>% Using</small>
        </td>
        <td><%= t("dashboard.device.table.summary", assignment: category.device_assignment,
          available: category.device_avalible, total: category.device_total) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/dashboard/_grid_request_dashboard.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= t "request.table.title" %></th>
      <th><%= t "request.table.description" %></th>
      <th><%= t "request.table.request_status" %></th>
      <th><%= t "request.table.for_user" %></th>
      <th><%= t "request.table.time_ago" %></th>
    </tr>
  </thead>
  <tbody>
    <% @requests.each do |request| %>
      <tr class="<%= generate_tag_color request %>" >
        <td class= "truncate"><%= request.title %></td>
        <td class= "truncate"><%= request.description %></td>
        <td><%= request.request_status_name %><%= link_to t("dashboard.request.check"),
          requests_path(request_status_id: request.request_status_id) %></td>
        <td class= "truncate"><%= request.for_user.name if request.for_user.present? %></td>
        <td><%= time_ago_in_words request.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/dashboard/_make_request.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= render "shared/user_info" %>
    </section>
  </aside>
</div>

app/views/dashboard/_request_cycle.html.erb
  <div id="request_cycle">
    <div class="x_panel tile fixed_height_320 overflow_hidden">
      <div class="x_title">
        <h3>
          <span><%= t "dashboard.request_overview" %> </span>
          <%= link_to t("dashboard.request.to_request"), requests_path %>
        </h3>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
      <% if @chartobj.present? && @chartobj[:have_data] %>
        <table class="chart w-100">
          <tr>
            <th class="w-37">
              <p><%= t "dashboard.request.chart" %></p>
            </th>
            <th>
              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                <p class=""><%= t "dashboard.request.status" %></p>
              </div>
              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                <p class=""><%= t "dashboard.request.summany" %></p>
              </div>
            </th>
          </tr>
          <tr>
            <td>
              <canvas id="canvas1"></canvas>
            </td>
            <td>
              <table class="tile_info">
                <% @chartobj[:labels].count.times do |i| %>
                  <tr>
                    <td>
                      <p>
                        <i class="fa fa-square <%= @chartobj[:colors][i] %>"></i>
                        <%= link_to @chartobj[:labels][i], requests_path(request_status_id: @chartobj[:request_status][i]) %>
                        </p>
                    </td>
                    <td><%= @chartobj[:datapercent][i] %>%</td>
                  </tr>
                <% end %>
              </table>
            </td>
          </tr>
        </table>
      <% else %>
        <div class="tile_info">
          <%= link_to t("dashboard.request.go_to_request"),  requests_path %>
        </div>
      <% end %>
      </div>
    </div>
  </div>

app/views/dashboard/_request_overview.html.erb
<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2><span><%= t "dashboard.request_overview" %></span></h2>
      <ul class="nav navbar-right panel_toolbox">
        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
        </li>
      </ul>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <%= render "request_cycle" %>
      <%= render "grid_request_dashboard" %>
    </div>
  </div>
</div>

app/views/dashboard/_top_overview.html.erb
<% if @requests.present? && @requests.any? %>
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2><span><%= t "dashboard.latest_request" %></span></h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <%= render "grid_request_dashboard" %>
      </div>
    </div>
  </div>
<% end %>
<% if current_user.can_manage_device && @device_categories.present? &&
    @device_categories.any? %>
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
      <div class="x_title">
        <h2><span><%= t "dashboard.hot_device_category" %></span></h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>
      <div class="x_content">
        <%= render "grid_device_dashboard" %>
      </div>
    </div>
  </div>
<% end %>

app/views/dashboard/index.html.erb
<% if logged_in? %>
  <div class="row">
  <%= render "chart_overview" %>
  </div>
  <div class="row">
  <%= render "top_overview" %>
  </div>
  <% if @current_user.is_admin %>
    <div class="row">
      <%= render "admin_overview" %>
    </div>
  <% end %>
<% else %>
  <div class="center jumbotron">
    <h1><%= t "home.title" %></h1>
    <h2><%= t "home.content" %></h2>
  </div>
<% end %>