config/routes.rb
Rails.application.routes.draw do
  resources :posts

  get "/changelanguage", to: "set_language#change_language"
  get "dashboard/index"
  get "device_code/show"
  get "get_device_code/show"
  get "assignment_device/show"
  get "group_category/show"
  get "device_assign/show"
  get "requests/new"
  get "requests/add_request_detail"
  root "dashboard#index"
  delete "/requestdetails", to: "request_details#destroy"
  get "/home", to: "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/help", to: "static_pages#help"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "show", to: :show, controller: "return_devices"
  put "update", to: :update, controller: "return_devices",
   collection: {update: :put}
  get "/dashboard_chart", to: "dashboard#request_chart"

  resources :users
  resources :devices
  resources :requests
  resources :request_details
  resources :assignments
  resources :notifications
  resources :request_status
  resources :my_devices, only: :index
  resources :user_setting, only: [:index, :update], collection: {update: :put}
  resources :return_devices, only: :index
  resources :device_history
  resources :user_groups
  resources :dashboard
  resources :device_categories
  resources :user_profiler
  resources :request_row
  resources :set_language
  resources :import
  resources :exports
  resources :printed_codes do
    patch :update, on: :collection
  end

  namespace :api do
    resources :devices, only: :index
  end

  put "create", to: :create, controller: "import",
    collection: {create: :put}
  mount ActionCable.server => "/cable"
  resources :export
end

app/controllers/device_history_controller.rb
class DeviceHistoryController < ApplicationController
  before_action :init_dropdown
  before_action :logged_in_user, :check_permision

  def index
    @search = AssignmentDetail.search(params[:q])
    @search.sorts = ["assignment_assignee_email","return_date asc", "assignments.created_at desc"]
    @using_histories = @search.result
      .paginate(page: params[:page], per_page: config_page_size)
  end

  private

  def check_permision
    unless current_user.can_manage_device
      flash[:danger] = t "permission.not_permisison"
      redirect_to root_url
    end
  end

  def init_dropdown
    @support = Supports::User.new current_user
  end
end

app/views/device_history/_grid_history.html.erb
<% if @using_histories.any? %>
  <table class="table table-hover table-fixed">
    <thead>
      <tr>
        <th class="width-30"><%= t "device_manager.table.header.device_code" %></th>
        <th class="width-30"><%= t "device_manager.table.header.category" %></th>
        <th class="width-30"><%= t "device_manager.table.header.from_date" %></th>
        <th class="width-30"><%= t "device_manager.table.header.to_date" %></th>
      </tr>
    </thead>
    <tbody>
      <% @using_histories.each do |using_history| %>
        <% if @curent_assignee.nil? || @curent_assignee != using_history.assignment_assignee_id %>
          <tr class="success">
            <td colspan="4">
              <%= t "device_manager.field_label.using_by" %>
              <%= link_to using_history.assignment_assignee_name,
                user_profiler_path(using_history.assignment_assignee_id), remote: true,
                data:{toggle: "modal", target: "#dms-popup", backdrop: "static"} %>
            </td>
          </tr>
        <% @curent_assignee = using_history.assignment_assignee_id %>
        <% end %>
        <tr>
          <td class="padding-left-3">
            <%= link_to "", device_history_index_path(q:
              {assignment_assignee_email_or_device_device_code_cont:
              using_history.device_device_code}),
              class: "glyphicon glyphicon-search",
              title: t("device_manager.field_label.history_tooltip",
              name: using_history.device_device_code) %>
            <%= link_to using_history.device_device_code, device_path(using_history.device_id), remote: true,
              data:{toggle: "modal", target: "#dms-popup", backdrop: "static"},
              title: t("device_manager.field_label.view_detail_device_tooltip",
              name: using_history.device_device_code) %>
          </td>
          <td>
            <%= using_history.device_device_category_name %>
          </td>
          <td>
            <%= l using_history.assignment.created_at, format: :date_format %>
          </td>
          <td>
            <% if using_history.return_date? %>
              <%= l using_history.return_date, format: :date_format %>
            <% else %>
              <span class="label badge">
                <%= t "device_manager.field_label.now"%>
              </span>
            <% end %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
  <%= will_paginate @using_histories %>
<% else %>
  <table class="table table-hover table-fixed">
    <thead>
      <tr>
        <th class="width-30"><%= t "device_manager.table.header.device_code" %></th>
        <th class="width-30"><%= t "device_manager.table.header.category" %></th>
        <th class="width-30"><%= t "device_manager.table.header.from_date" %></th>
        <th class="width-30"><%= t "device_manager.table.header.to_date" %></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td colspan="4" class="taC">
          <%= t "device_manager.table.message.device_not_exist_using_history" %>
        </td>
      </tr>
      </tbody>
  </table>
<% end %>

app/views/device_history/index.html.erb
<div class="row">
  <%= search_form_for @search, url: device_history_index_path, id: "form-submit" do |f| %>
    <div class="row padding-left-1">
      <div class="col-lg-2 text-right">
        <label class="form-control"><%= t "device_manager.field_label.key_search" %></label>
      </div>
      <div class="col-lg-4">
        <%= f.text_field :assignment_assignee_email_or_device_device_code_cont, class: "form-control",
          placeholder: t("device_manager.field_label.place_holder"), id: "key_search" %>
        <span id="searchclear" class="glyphicon glyphicon-remove-circle"
         onclick="clear_text_box_search();"></span>
      </div>
    </div>
  <% end %>
</div>
<br/>
<%= render "grid_history" %>