config/routes.rb
Rails.application.routes.draw do
  resources :posts

  get "/changelanguage", to: "set_language#change_language"
  get "dashboard/index"
  get "device_code/show"
  get "get_device_code/show"
  get "assignment_device/show"
  get "group_category/show"
  get "device_assign/show"
  get "requests/new"
  get "requests/add_request_detail"
  root "dashboard#index"
  delete "/requestdetails", to: "request_details#destroy"
  get "/home", to: "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/help", to: "static_pages#help"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "show", to: :show, controller: "return_devices"
  put "update", to: :update, controller: "return_devices",
   collection: {update: :put}
  get "/dashboard_chart", to: "dashboard#request_chart"

  resources :users
  resources :devices
  resources :requests
  resources :request_details
  resources :assignments
  resources :notifications
  resources :request_status
  resources :my_devices, only: :index
  resources :user_setting, only: [:index, :update], collection: {update: :put}
  resources :return_devices, only: :index
  resources :device_history
  resources :user_groups
  resources :dashboard
  resources :device_categories
  resources :user_profiler
  resources :request_row
  resources :set_language
  resources :import
  resources :exports
  resources :printed_codes do
    patch :update, on: :collection
  end

  namespace :api do
    resources :devices, only: :index
  end

  put "create", to: :create, controller: "import",
    collection: {create: :put}
  mount ActionCable.server => "/cable"
  resources :export
end

app/models/notification.rb
class Notification < ApplicationRecord
  after_create_commit :raise_notification

  scope :default_sort, ->{order created_at: :desc}

  scope :un_read, ->user_id do
    where "checked = false AND reciver_id = ?", user_id
  end

  scope :by_current_user, ->user_id do
    where reciver_id: user_id
  end

  scope :sort_by_checked, ->checked do
    order checked: :asc if checked.present? && checked
  end

  scope :created_from_date, ->(from_date) do
    where "CAST(created_at AS DATE) >= CAST(? AS DATE)",
     from_date if from_date.present?
  end

  scope :created_to_date, ->(to_date) do
    where "CAST(created_at AS DATE) <= CAST(? AS DATE)",
     to_date if to_date.present?
  end

  scope :sender_by, ->user_id do
    where sender_id: user_id if user_id.present?
  end

  private

  def raise_notification
    NotificationBroadcastJob.perform_later(reciver_id, Notification.un_read(reciver_id).count, self)
    NotificationMailer.notification_mail id
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :logged_in_user
  before_action :init_notification, only: :show
  before_action :init_data

  def index
    @list_notifications = Notification.by_current_user(current_user.id)
      .created_from_date(params[:from_date])
      .created_to_date(params[:to_date])
      .sender_by(params[:sender_id])
      .default_sort.paginate page: params[:page]
  end

  def show
    @notification.checked = true
    if @notification.save
      redirect_to @notification.link
    end
  end

  private

  def init_notification
    @notification = Notification.find_by id: params[:id]
    unless @notification
      flash[:danger] = t "notification.message.notification_not_found"
      redirect_to root_path
    end
  end

  def init_data
    @support = Supports::User.new current_user
  end
end

app/views/notifications/_counter.html.erb
<li>
  <%= image_tag("notification_bell.svg") %>
  <span  id="notification-counter"><%= counter %></span>
</li>

app/views/notifications/_notification.html.erb
<% if notification %>
    <li class="<%= notification.checked? ? '' : 'un-read' %> truncate">
      <%= link_to notification.body, notification %>
      <span class="glyphicon
        <%= notification.checked? ? 'glyphicon-ok' : '' %> padding-left-1">
      </span>
    </li>
<% end %>

app/views/notifications/_notification_center.html.erb
<ul class="notificator">
  <%= link_to render("notifications/counter", counter: notifications.present? ? Notification.un_read(current_user.id).count : 0), "#", {id: "open_notification"} %>
  <div id="notificationContainer">
    <div id="notificationTitle"><%= t "notification.label.header" %></div>
    <div id="notificationsBody" class="notifications">
      <ul id="notificationList">
        <%= render notifications %>
      </ul>
    </div>
    <div id="notificationFooter">
      <%= link_to t("notification.label.view_all"), notifications_path %>
    </div>
  </div>
</ul>

app/views/notifications/index.html.erb
<div class="notification-header">
  <%= t "notification.table_header.notification" %>
</div>
<br/>
<div class="row">
  <%= form_tag "", id: "form-submit", method: :get do %>
    <div class="row">
      <div class="col-lg-1 text-right"></div>
      <div class="col-lg-2 text-right">
        <label class="form-control"><%= t "notification.index.label_sender" %></label>
      </div>
      <div class="col-lg-8">
        <%= select_tag(:sender_id, options_for_select(@support.all_users
          .collect{|user|[user.name, user.id]},
          params[:sender_id]), include_blank: Settings.all,
          class: "chosen-select") %>
      </div>
    </div>
    <br/>
    <div class="row">
      <div class="col-lg-1 text-right"></div>
      <div class="col-lg-2 text-right">
        <label class="form-control"><%= t "notification.index.label_created_from" %></label>
      </div>
      <div class="col-lg-3">
        <%= text_field_tag :from_date, params[:from_date],
          {class: "datepicker form-control" } %>
      </div>
       <div class="col-lg-2 text-right">
         <label class="form-control"><%= t "notification.index.label_created_to" %></label>
      </div>
      <div class="col-lg-3">
        <%= text_field_tag :to_date, params[:to_date],
          {class: "datepicker form-control" } %>
      </div>
    </div>
    <br/>
    <div class="row taR">
      <div class="col-lg-1 text-right"></div>
      <div class="col-lg-10">
        <button type="button" class="btn btn-primary btn-notification" onclick="changeSearchForm_noti();">
          <%= t "notification.index.button_search" %></button>
      </div>
    </div>
  <% end %>

</div>
<br/>
<% if @list_notifications.any? %>
    <table class="table table-hover" style="table-layout: fixed;">
      <tbody>
        <% @list_notifications.each do |notification| %>
          <tr>
            <td class="<%= notification.checked? ? '' : 'un-read' %>">
              <%= link_to notification.body, notification, {class: "font-size-20"} %>
              <div class="padding-left-1">
                <span>
                  <%= t "notification.label.from "%>
                  <b>
                    <%= @support.created_by notification.sender_id %>
                  </b
                  <%= t "notification.label.at "%>
                  <b>
                    <%= l notification.created_at, format: :date_format %>
                  </b>
                </span>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <%= will_paginate @list_notifications %>
<% end %>