config/routes.rb
Rails.application.routes.draw do
  resources :posts

  get "/changelanguage", to: "set_language#change_language"
  get "dashboard/index"
  get "device_code/show"
  get "get_device_code/show"
  get "assignment_device/show"
  get "group_category/show"
  get "device_assign/show"
  get "requests/new"
  get "requests/add_request_detail"
  root "dashboard#index"
  delete "/requestdetails", to: "request_details#destroy"
  get "/home", to: "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/help", to: "static_pages#help"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "show", to: :show, controller: "return_devices"
  put "update", to: :update, controller: "return_devices",
   collection: {update: :put}
  get "/dashboard_chart", to: "dashboard#request_chart"

  resources :users
  resources :devices
  resources :requests
  resources :request_details
  resources :assignments
  resources :notifications
  resources :request_status
  resources :my_devices, only: :index
  resources :user_setting, only: [:index, :update], collection: {update: :put}
  resources :return_devices, only: :index
  resources :device_history
  resources :user_groups
  resources :dashboard
  resources :device_categories
  resources :user_profiler
  resources :request_row
  resources :set_language
  resources :import
  resources :exports
  resources :printed_codes do
    patch :update, on: :collection
  end

  namespace :api do
    resources :devices, only: :index
  end

  put "create", to: :create, controller: "import",
    collection: {create: :put}
  mount ActionCable.server => "/cable"
  resources :export
end

app/models/request.rb
class Request < ApplicationRecord
  attr_accessor :creater, :updater, :readonly, :assignee, :request_status_name

  belongs_to :request_type
  belongs_to :request_status
  belongs_to :for_user, class_name: User.name
  has_many :request_details, dependent: :destroy, inverse_of: :request
  has_many :devices, through: :request_details

  delegate :name, to: :request_status, prefix: true, allow_nil: true

  validates :title, :description, presence: true

  accepts_nested_attributes_for :request_details,
    reject_if: proc{|attributes| attributes[:description].blank?}

  after_create_commit :create_hitory_for_create
  after_update_commit :create_hitory_for_update
  after_initialize :create_extend_data
  after_save :create_notification

  scope :from_excel, -> do
    where "id in (select r.id from requests as r left join users as u on r.for_user_id = u.id
      where u.from_excel = true)"
  end
  scope :order_by_time, ->{order created_at: :desc, updated_at: :desc}
  scope :sort_by_status, ->{sort_by request_status_id}
  scope :of_actor, ->user_id do
    if user_id.present?
      where "id in (select r.id from requests as r
        where r.assignee_id = ? or r.created_by = ? or r.updated_by = ?
        or r.for_user_id = ?)", user_id, user_id, user_id, user_id
    end
  end

  class << self
    def convert_like param
      "#{param}%"
    end
  end

  scope :of_for_user, ->user_id, parent_path, user do
    if user_id.present?
      where for_user_id: user_id
    else
      request_manage parent_path, user
    end
  end

  scope :with_status, ->request_status_id do
    where request_status_id: request_status_id if request_status_id.present?
  end

  scope :request_of_below_staff, ->parent_path, current_id do
    where "for_user_id in (select u.id from users as u left join user_groups as
      ug on ug.user_id = u.id left join groups as g on g.id = ug.group_id where
      g.parent_path LIKE ? and ug.is_default_group = true )", convert_like(parent_path)
  end

  scope :request_manage, ->parent_path, user do
    if user.present?
      case user.current_permission
      when Settings.action.approve
        where "for_user_id in (select u.id from users as u left join user_groups as
          ug on ug.user_id = u.id left join groups as g on g.id = ug.group_id where
          g.parent_path LIKE ? and ug.is_default_group = true) or for_user_id = ?", convert_like(parent_path), user.id
      when Settings.action.waiting_done
        where "request_status_id >= ? or (request_status_id = ? and updated_by = ?)",
          Settings.request_status.approved, Settings.request_status.cancelled, user.id
      when Settings.action.done
        where request_status_id: [Settings.request_status.waiting_done, Settings.request_status.done]
      end
    end
  end

  scope :request_not_self, -> user do
    where.not for_user_id: user.id
  end

  scope :request_manage_request_approve, ->parent_path, user do
    where "for_user_id in (select u.id from users as u left join user_groups as
      ug on ug.user_id = u.id left join groups as g on g.id = ug.group_id where
      g.parent_path LIKE ?)", convert_like(parent_path)
  end

  scope :request_manage_request_waiting_done, ->parent_path, user do
    where "request_status_id >= ? or (request_status_id = ? and updated_by = ?)",
      Settings.request_status.approved, Settings.request_status.cancelled, user.id
  end

  scope :request_manage_request_done, ->parent_path, user do
    where request_status_id: [Settings.request_status.waiting_done, Settings.request_status.done]
  end

  scope :request_can_access, ->parent_path, current_id do
    where "for_user_id in (select u.id from users as u left join user_groups as
      ug on ug.user_id = u.id left join groups as g on g.id = ug.group_id where
      g.parent_path LIKE ?) OR id in (select r.id from requests as r where
      r.assignee_id = ?) OR request_status_id != 1",
      convert_like(parent_path), current_id
  end

  scope :of_request_type, ->request_type_id do
    where request_type_id: request_type_id if request_type_id.present?
  end

  scope :of_request_status, ->request_status_id do
    where request_status_id: request_status_id if request_status_id.present?
  end

  def is_approved?
    request_status_id == Settings.request_status.approved
  end

  def is_need_approve?
    request_status_id == Settings.request_status.waiting_approve ||
    request_status_id == Settings.request_status.cancelled
  end

  def show_approve_request? user
    user.can_approve && request_status_id == Settings.request_status.waiting_approve
  end

  def show_cancel_request? user
    case request_status_id
    when Settings.request_status.waiting_approve
      user.can_make_request && created_by == user.id || user.can_approve
    when Settings.request_status.approved
      user.can_waiting_done || (user.can_approve && user.id == updated_by)
    else
      false
    end
  end

  def show_reupdate? user
    user.current_permission.present? && user.id == created_by &&
    request_status_id == Settings.request_status.cancelled &&
    (user.current_permission == Settings.action.create || user.current_permission == Settings.action.approve)
  end

  def show_revert_waiting? user
    user.current_permission == Settings.action.approve && user.id == updated_by &&
    user.id != created_by && request_status_id == Settings.request_status.approved
  end
  def show_approve_request? user
    user.can_approve && request_status_id == Settings.request_status.waiting_approve
  end

  def show_waiting_approve? user
    user.can_make_request && request_status_id == Settings.request_status.cancelled
  end
  def show_waiting_done? user
    user.can_waiting_done && request_status_id == Settings.request_status.approved
  end

  def show_assignment_request? user
    user.can_done && request_status_id == Settings.request_status.waiting_done
  end

  def allow_change_status? user
    id.present? && (user.can_approve || allow_edit?(user))
  end

  def allow_edit? user
    user_staff_edit_request?(user) || user_manager_edit_request?(user) ||
    user_manager_bo_edit_request?(user)
  end

  def user_staff_edit_request? user
    user.can_make_request && user.id == created_by &&
    request_status_id <= Settings.request_status.waiting_approve
  end

  def user_manager_edit_request? user
    staff = User.below_staff(user.default_parent_path, user.id).find_by id: created_by
    user.can_approve && (user.id == created_by || staff.present?) &&
    (request_status_id == Settings.request_status.waiting_approve ||
    (request_status_id == Settings.request_status.cancelled && created_by == user.id) ||
    (request_status_id == Settings.request_status.approved &&
    (for_user_id == user.id || updated_by == user.id)))
  end

  def user_manager_bo_edit_request? user
    user.can_waiting_done && request_status_id == Settings.request_status.approved
  end

  def owner? user
    return true if id.nil? || created_by.present? && created_by == user.id
    false
  end

  def status_reupdate user
    case user.current_permission
    when Settings.action.create
      Settings.request_status.waiting_approve
    when Settings.action.approve
      if request_status_id == Settings.request_status.approved
        Settings.request_status.waiting_approve
      else
        Settings.request_status.approved
      end
    end
  end

  def title_update user
    case user.current_permission
    when Settings.action.approve
      if request_status_id == Settings.request_status.approved
        I18n.t("request.action.re_back_waiting")
      else
        I18n.t("request.action.re_approve")
      end
    when Settings.action.create
      I18n.t("request.action.re_send")
    end
  end

  def send_notify_list lst_users
    if created_at == updated_at
      message = I18n.t("notification.message.request_message",
        request_title: title, action: I18n.t("notification.action.created"))
    else
      message = I18n.t("notification.message.request_message_update",
        request_title: title, action: I18n.t("notification.action.updated"), status: request_status.name)
    end
    lst_users.each do |user|
      create_notify updated_by, user.id,
        message, Rails.application.routes.url_helpers.requests_path
    end
  end

  private

  def create_extend_data
    self.creater = User.find_by id: created_by
    self.updater = User.find_by id: updated_by
    self.assignee = User.find_by id: assignee_id if assignee_id.present?
    self.request_status_name = get_request_status_name request_status_id
  end

  def create_history action
    user_name = get_created_name created_by
    content = I18n.t("history.request",action: action, name: user_name)
    history_data = {"content": content, "status": request_status_name}
    create_hitory id, history_data.to_json, Settings.history_type.request
  end

  def create_notification
    if created_at == updated_at
      message = I18n.t("notification.message.request_message",
        request_title: title, action: I18n.t("notification.action.created"))
    else
      message = I18n.t("notification.message.request_message_update",
        request_title: title, action: I18n.t("notification.action.updated"), status: request_status.name)
    end
    create_notify updated_by, for_user_id,
      message, Rails.application.routes.url_helpers.requests_path
  end


  def get_request_status_name request_status_id
    case request_status_id
    when Settings.request_status.cancelled
      I18n.t("request_status.cancelled")
    when Settings.request_status.waiting_approve
      I18n.t("request_status.waiting_approve")
    when Settings.request_status.approved
      I18n.t("request_status.approved")
    when Settings.request_status.waiting_done
      I18n.t("request_status.waiting_done")
    when Settings.request_status.done
      I18n.t("request_status.done")
    end
  end
end

app/models/request_type.rb
class RequestType < ApplicationRecord
  has_many :requests, dependent: :destroy

  enum type: {request: 1, return: 2, borrow: 3}
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :init_request, only: [:edit, :update, :show]
  before_action :init_support, expect: [:destroy, :show]
  before_action :logged_in_user, :init_extend_data

  def index
    load_request params[:manager_request]
    if params[:isAjax].present? or params[:page].present?
      respond_to do |format|
        format.js
      end
    end
  end

  def new
    @request = Request.new
    respond_to do |format|
      format.js
    end
  end

  def create
    update_before_save
    respond_to do |format|
      update_create_request @request
      if @request.save
        flash[:success] = t "action_message.create_success"
        send_notifycation @request
        @manage_tag_selected = @current_user.id == @request.for_user_id ? false : true
        load_request params[:manager_request]
      else
        flash[:danger] = t "action_message.create_fail"
      end
      format.js
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    update_before_save
    request_form = RequestForm.new request_params
    if request_form.check_logic_request request_params, @request
      @request.update_attributes request_params
      respond_to do |format|
        format.js
        if @request.errors.empty?
          flash.now[:success] = t "action_message.update_success"
          send_notifycation @request
          load_request params[:manager_request]
        else
          flash[:danger] = t "action_message.update_fail"
        end
      end
    else
      flash[:danger] = t "request.update_conflict"
    end
  end

  def show
    @request.readonly = true
    if @request.request_status_id == Settings.request_status.done
      @assignment = Assignment.find_by request_id: @request.id
    end
    unless params[:from_app].present?
      respond_to do |format|
        format.js
      end
    end
  end

  def add_request_detail
    respond_to do |format|
      format.js
    end
  end

  def destroy; end

  private

  def send_notifycation request
    case request.request_status_id
    when Settings.request_status.waiting_approve
      users = user_can_approve
      users = users.select {|u| @current_user.default_parent_path.index(u.default_parent_path) == 0}
      request.send_notify_list users
    when Settings.request_status.approved
      request.send_notify_list user_can_waiting_done
    when Settings.request_status.waiting_done
      request.send_notify_list user_can_done_request
    end
  end

  def load_request manager_request
    get_requests manager_request
    get_my_requests manager_request
  end

  def update_before_save
    @request = Request.new request_params unless @request
    @request.created_by = current_user.id unless @request.id
    @request.updated_by = current_user.id
  end

  def request_params
    params.require(:request).permit :title, :description, :request_type_id,
      :request_status_id, :for_user_id, :assignee_id,
      request_details_attributes: [:id, :description, :device_category_id,
        :number]
  end

  def request_status_params
    params.require(:request).permit :request_status_id, :id
  end

  def get_requests manager_request
    page = manager_request == Settings.boolean_params.true ? params[:page] : 1
    @requests = Request.request_manage(@current_user.default_parent_path, @current_user)
      .request_not_self(@current_user).of_actor(params[:relative_id])
      .of_request_status(params[:request_status_id])
      .order_by_time.paginate page: page, per_page: config_page_size
  end

  def get_my_requests manager_request
    page = manager_request == Settings.boolean_params.false ? params[:page] : 1
    @my_requests = Request.of_for_user(@current_user.id, @current_user.default_parent_path, @current_user).order_by_time
      .of_actor(params[:relative_id])
      .of_request_status(params[:request_status_id]).order_by_time
      .paginate page: page, per_page: config_page_size
  end

  def init_support
    @support ||= Supports::User.new current_user
  end

  def init_request
    @request = Request.find_by id: params[:id]
    unless @request
      flash[:danger] = t "request_manager.not_exist"
      redirect_to requests_path
    end
  end

  def update_create_request request
    request.request_type_id = Settings.type.request
    if @current_user.can_approve
      request.request_status_id = Settings.request_status.approved
    else
      request.request_status_id = Settings.request_status.waiting_approve
    end
  end

  def init_extend_data
    @manage_tag_selected = @current_user.can_manage_request
  end
end

app/views/requests/_action.html.erb
<div class="row">
  <%= form_tag(request_row_index_path, id: "form-submit-action"+ request.id.to_s, method: :get, remote: true) do %>
    <%= hidden_field_tag "request_status_id", request.request_status_id %>
    <%= hidden_field_tag "id", request.id %>
    <div class="btn-group done_center" data-toggle="buttons"
      onchange="update_request(this,<%= request.id %>,
      '<%= request_status_path(request) %>')">
      <% if request.show_cancel_request? @current_user %>
        <label class="btn btn-default">
          <%= radio_button("post", "options #{request.id}",
            Settings.request_status.cancelled) %>
          <%= t "request.action.cancel" %>
        </label>
      <% end %>
      <% if request.show_reupdate? @current_user %>
        <label class="btn btn-default %>">
          <%= radio_button("post", "options #{request.id}",
            request.status_reupdate(current_user)) %>
          <%= request.title_update current_user %>
        </label>
      <% end %>
      <% if request.show_revert_waiting? @current_user %>
        <label class="btn btn-default %>">
          <%= radio_button("post", "options #{request.id}",
            request.status_reupdate(current_user)) %>
          <%= request.title_update current_user %>
        </label>
      <% end %>
      <% if request.show_approve_request? @current_user %>
        <label class="btn btn-default">
          <%= radio_button("post", "options #{request.id}",
            Settings.request_status.approved) %>
          <%= t "request.action.approve" %>
        </label>
      <% end %>
      <% if request.show_waiting_done? @current_user %>
        <label class="btn btn-default">
          <%= radio_button("post", "options #{request.id}",
            Settings.request_status.waiting_done) %>
          <%= t "request.action.waiting_done" %>
        </label>
      <% end %>
    </div>
  <% end %>
</div>

app/views/requests/_another_request.html.erb
<div class="content">
  <div id="another_request", class="grid_table">
    <%= render "grid_request" %>
  </div>
</div>

app/views/requests/_form_request.html.erb
<% if @request.readonly %>
  <%= render "requests/form_request_readonly" %>
<% else %>
  <%= form_for @request, remote: true do |f| %>
    <div id="error"></div>
    <div class="input-field col s6">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="input-field col s6">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>
    </div>
    <div class="input-field col s6">
      <%= f.label t "request.table.request_for" %>
      <% if @request.owner? @current_user %>
        <% if @request.for_user_id == @current_user.id %>
          <%= f.collection_select :for_user_id, @support.below_staffs, :id, :name,
          {}, {class: "form-control", disabled: "disabled"} %>
        <% else %>
          <%= f.collection_select :for_user_id, @support.below_staffs, :id, :name,
          {}, {class: "chosen-select form-control"} %>
        <% end %>
      <% else %>
        <%= f.collection_select :for_user_id, @support.all_users, :id, :name,
          {}, {class: "form-control", disabled: "disabled"} %>
      <% end %>
    </div>
    <% if @current_user.can_assign_to? %>
      <div class="input-field col s6">
        <%= f.label t "request.table.assignee" %>
        <%= f.collection_select :assignee_id, @support.lst_assignee(@current_user, @request), :id,
          :name, {include_blank: Settings.none}, {class: "chosen-select"} %>
      </div>
    <% end %>
    <% if @request.allow_change_status? @current_user %>
      <div class="input-field col s6">
        <%= f.label t "request.table.request_status" %>
        <%= f.collection_select :request_status_id, @support.lst_request_status(@current_user, @request), :id, :name,
          {}, {class: "form-control"} %>
      </div>
    <% end %>
    <div class="row line_top">
      <%= link_to t("request.add_request_detail"),
        requests_add_request_detail_path,
        class: "btn btn-primary btn_add_detail", remote: true %>
    </div>

    <input id="request_details" name="request_details" type="hidden" />
    <div class="popup-details-max-height">
      <table id="tbl_request_details" class="table table-hover">
        <thead>
          <tr>
            <th><%= t "request_detail.description" %></th>
            <th><%= t "request_detail.device_category" %></th>
            <th><%= t "request_detail.number" %></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
           <%= f.fields_for :request_details do |request_detail| %>
            <tr>
              <td> <%= request_detail.text_area :description, class: "height-34 form-control" %> </td>
              <td>
                <%= request_detail.collection_select :device_category_id, @support.device_categories, :id, :name, {},
                {class: "form-control"} %>
              </td>
              <td><%= request_detail.text_field :number, class: "form-control", type: "number" %></td>
              <td>
                <a class="glyphicon glyphicon-remove padding-top-component"
                  onclick="remove_request_detail(this, 'tbl_request_details', 'request','request_detail')">
                </a>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">
        <%= t "action.close" %>
      </button>
      <button type="submit" class="btn btn-primary">
        <%= t "action.save" %>
      </button>
    </div>
  <% end %>
<% end %>

app/views/requests/_form_request_readonly.html.erb
<div>
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
      <a href="#request_info" aria-controls="request_info"
        role="tab" data-toggle="tab"><%= t "request.tab.request_info" %></a>
    </li>
    <li role="presentation">
      <a href="#device_assignment" aria-controls="device_assignment"
        role="tab" data-toggle="tab"><%= t "request.tab.device_assignment" %></a>
    </li>
  </ul>
  <div class="tab-content popup-max-height">
    <div role="tabpanel" class="tab-pane active" id="request_info">
      <%= render "request_info" %>
    </div>
    <div role="tabpanel" class="tab-pane" id="device_assignment">
      <%= render "device_assignment" %>
    </div>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">
      <%= t "device_manager.button_close_text" %>
    </button>
   </div>
</div>

app/views/requests/_grid_content.html.erb
<ul class="nav nav-tabs" role="tablist">
  <% if @current_user.can_manage_request %>
    <li role="presentation" class= <%= @manage_tag_selected ? "active" : "" %>>
      <a href="#another_request" aria-controls="another_request"
        role="tab" data-toggle="tab"><%= t "request.tab.another_request" %></a>
    </li>
  <% end %>
  <li role="presentation" class= <%= @manage_tag_selected ? "" : "active" %>>
    <a href="#private_request" aria-controls="private_request"
      role="tab" data-toggle="tab"><%= t "request.tab.my_title" %></a>
  </li>
</ul>

<div class="tab-content">
  <% if @current_user.can_manage_request %>
    <div role="tabpanel" class="tab-pane <%= @manage_tag_selected ? "active" : "" %>" id="another_request">
      <%= render "another_request" %>
    </div>
  <% end %>

  <div role="tabpanel" class="tab-pane <%= @manage_tag_selected ? "" : "active" %>" id="private_request">
    <%= render "private_request" %>
  </div>
</div>

app/views/requests/_grid_request.html.erb
<% if @requests.any? %>
  <table class="table table-hover table-striped">
    <thead>
      <tr>
        <th class="truncate"><%= t "request.table.title" %></th>
        <th><%= t "request.table.request_status" %></th>
        <th class="request-action"><%= t "request.table.request_action" %></th>
        <th class="truncate"><%= t "request.table.assignee" %></th>
        <th class="truncate"><%= t "request.table.for_user" %></th>
        <th class="truncate"><%= t "request.table.updated_by" %></th>
        <th><%= t "created_at" %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @requests.each do |request| %>
        <tr id="<%= request.id %>" data-toggle="tooltip" title="<%= request.description %>">
          <%= render partial: "request_row", locals: {request: request} %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= js_will_paginate @requests, params: {manager_request: 1} %>
<% end %>

app/views/requests/_request_info.html.erb
<div class="input-field col s6">
  <%= label_tag t "request.table.description", {class: "form-control"} %>
  <%= text_field_tag @request.description, @request.description,
    {class: "form-control", disabled: "disabled"} %>
</div>

<div class="input-field col s6">
  <%= label_tag t "request.table.title", {class: "form-control"} %>
  <%= text_area_tag @request.title, @request.title,
    {class: "form-control", disabled: "disabled"} %>
</div>

<div class="input-field col s6">
  <%= label_tag t "request.table.request_status", {class: "form-control"} %>
  <%= text_field_tag @request.request_status_name, @request.request_status_name,
    {class: "form-control", disabled: "disabled"} %>
</div>

<div class="input-field col s6">
  <%= label_tag t "request.table.request_for", {class: "form-control"} %>
  <%= text_field_tag @request.for_user.present? ? @request.for_user.name : "" , @request.for_user.present? ? @request.for_user.name : "",
    {class: "form-control", disabled: "disabled"} %>
</div>

<div class="input-field col s6">
  <%= label_tag t "request.table.created_by", {class: "form-control"} %>
  <%= text_field_tag @request.creater.present? ? @request.creater.name : "" , @request.creater.present? ? @request.creater.name : "" ,
    {class: "form-control", disabled: "disabled"} %>
</div>

<div class="input-field col s6">
  <%= label_tag t "request.table.updated_by", {class: "form-control"} %>
  <%= text_field_tag @request.updater.present? ? @request.updater.name : "", @request.updater.present? ? @request.updater.name : "",
    {class: "form-control", disabled: "disabled"} %>
</div>

<table id="tbl_request_details" class="table table-hover">
  <thead>
    <tr>
      <th><%= t "request_detail.description" %></th>
      <th><%= t "request_detail.device_category" %></th>
      <th><%= t "request_detail.number" %></th>
    </tr>
  </thead>

  <tbody>
    <% @request.request_details.each do |request_detail| %>
      <tr>
        <td>
          <%= text_area_tag  request_detail.description,
            request_detail.description, {class: "form-control",
              disabled: "disabled"} %></td>
        <td>
          <%= text_field_tag  request_detail.device_category.name,
            request_detail.device_category.name, {class: "form-control",
              disabled: "disabled"} %></td>
        <td> <%= text_field_tag  request_detail.number, request_detail.number,
          {class: "form-control", disabled: "disabled"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/requests/_request_row.html.erb
<td class="truncate"><%= link_to request.title, request_path(request.id), remote: true,
  data: {toggle: "modal", target: "#dms-popup", backdrop: "static"} %></td>
<td><%= request.request_status_name %></td>
<td class="request_status action">
  <%= render "action", request: request %>
</td>
<td class="truncate"><%= request.assignee.name if request.assignee.present? %></td>
<td class="truncate"><%= request.for_user.name if request.for_user.present? %></td>
<td class="truncate"><%= request.updater.name if request.updater.present? %></td>
<td><%= l request.created_at, format: :long %></td>
<td>
  <% if request.show_assignment_request? @current_user %>
    <%= link_to "", new_assignment_path(request_id: request.id), remote: true,
    class: "glyphicon glyphicon-plus",
    data: {toggle: "modal", target: "#dms-popup"} %>
  <% end %>
  <% if request.allow_edit? @current_user %>
    <%= link_to "", edit_request_path(request), remote: true,
      class: "glyphicon glyphicon-pencil btn btn-warning",
      data: {toggle: "modal", target: "#dms-popup"} %>
  <% end %>
</td>

app/views/requests/_search_form.html.erb
<div class="content">
  <div class="row">
    <%= form_tag("", id: "form-submit", method: :get, remote: true) do %>
      <%= hidden_field_tag "isAjax", true %>
      <div class="col-lg-1 text-center">
        <%= t "request_manager.search.relative_to" %>
      </div>
      <div class="col-lg-3 text-center">
        <%= select_tag(:relative_id, options_for_select(@support.below_staffs
          .collect{|staff| [staff.name, staff.id]},
          params[:relative_id]), include_blank: Settings.all,
          class: "form-control chosen-select", onChange: "changeSearchForm()") %>
      </div>
      <div class="col-lg-1 text-center">
        <%= t "request_manager.search.request_status" %>
      </div>
      <div class="col-lg-3 text-center">
        <%= select_tag(:request_status_id, options_for_select(@support.request_statuses_search
          .collect{|request_status| [request_status.name, request_status.id]},
          params[:request_status_id]), include_blank: Settings.all,
          class: "form-control request-status", onChange: "changeSearchForm()") %>
      </div>
    <% end %>
  </div>
</div>

app/views/requests/add_request_detail.js.erb
$('#tbl_request_details tbody').append('<%= j render "request_details/form_request_detail.html" %>');
resetIndex("tbl_request_details","request","request_detail");

app/views/requests/create.js.erb
<% if @request.errors.any? %>
  $('#error').html('<%= j render "shared/error_messages", object: @request %>')
<% else %>
  $('#dms-popup').modal('toggle');
  $('#request_content_grid').html("<%= j render(partial: 'requests/grid_content') %>");
<% end %>

app/views/requests/edit.js.erb
$('.modal-body').html('<%= j render "requests/form_request" %>')
$('#header').text('<%=  @request.title %>')
set_up_chosen();

app/views/requests/show.js.erb
$('.modal-body').html('<%= j render "requests/form_request" %>')
$('#header').text('<%= @request.title %>')
$('#div-button-close').show();

app/views/requests/update.js.erb
<% if @request.errors.any? %>
  $('#error').html('<%= j render "shared/error_messages", object: @request %>')
<% else %>
  $('#dms-popup').modal('toggle');
  <% if @request.for_user_id != @current_user.id %>
    $('#private_request').html("<%= j render partial: 'requests/grid_my_request' %>");
    $('#another_request').html("<%= j render partial: 'requests/grid_request' %>");
  <% else %>
    $('#'+ <%=@request.id%>).html('<%= j render "request_row/request_row" %>')
  <% end %>
<% end %>